
import { ClaudeParser } from '../src/services/readers/claude-parser';

describe('ClaudeParser', () => {
    describe('parseSession', () => {
        it('should parse a valid session JSONL', () => {
            const jsonl = `
{"type":"user","message":{"role":"user","content":"hello"},"sessionId":"session-1","timestamp":"2023-01-01T12:00:00Z"}
{"type":"assistant","message":{"role":"assistant","content":"hi"},"sessionId":"session-1","timestamp":"2023-01-01T12:00:01Z"}
            `;

            const session = ClaudeParser.parseSession(jsonl);
            expect(session).toBeDefined();
            expect(session?.id).toBe('session-1');
            expect(session?.messages).toHaveLength(2);
            expect(session?.messages[0].content).toBe('hello');
            expect(session?.messages[1].content).toBe('hi');
        });

        it('should return null for empty content', () => {
            const session = ClaudeParser.parseSession('');
            expect(session).toBeNull();
        });
    });

    describe('parseMessage', () => {
        it('should parse user message with command XML', () => {
            const event = {
                type: 'user',
                message: {
                    role: 'user',
                    content: '<command-name>/help</command-name>'
                },
                timestamp: '2023-01-01T12:00:00Z'
            };

            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg?.role).toBe('user');
            expect(msg?.content).toBe('> /help');
        });

        it('should parse stdout XML', () => {
            const event = {
                type: 'user',
                message: {
                    role: 'user',
                    content: '<local-command-stdout>some output</local-command-stdout>'
                },
                timestamp: '2023-01-01T12:00:00Z'
            };

            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg?.content).toBe('> ⎿ some output');
        });

        it('should parse assistant message with tool use', () => {
            const event = {
                type: 'assistant',
                message: {
                    role: 'assistant',
                    content: [
                        { type: 'text', text: 'Let me check.' },
                        { type: 'tool_use', name: 'ls' }
                    ],
                    model: 'claude-3-opus'
                }
            };

            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg?.role).toBe('assistant');
            expect(msg?.content).toBe('Let me check.\n'); // text only, tool usage hidden in content
            expect(msg?.metadata?.model).toBe('claude-3-opus');
            expect(msg?.metadata?.tool_calls).toEqual(['ls']);
        });

        it('should filter out messages with ONLY tool use', () => {
            const event = {
                type: 'assistant',
                message: {
                    role: 'assistant',
                    content: [
                        { type: 'tool_use', name: 'ls' } // No text
                    ]
                }
            };
            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg).toBeNull();
        });

        it('should parse error message', () => {
            const event = {
                type: 'assistant',
                isApiErrorMessage: true,
                error: 'authentication_failed',
                message: {
                    role: 'assistant',
                    content: [{ type: 'text', text: 'Invalid API Key' }]
                }
            };

            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg?.role).toBe('assistant');
            // It should prefer the content if available
            expect(msg?.content).toBe('Invalid API Key');
        });

        it('should parse summary event', () => {
            const event = {
                type: 'summary',
                summary: 'API Error: 403 Permission Denied',
                timestamp: '2023-01-01T12:00:00Z'
            };

            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg?.role).toBe('assistant');
            expect(msg?.content).toBe('[Summary] API Error: 403 Permission Denied');
        });

        it('should not skip meta messages with content', () => {
            const event = {
                type: 'user',
                isMeta: true,
                message: {
                    role: 'user',
                    content: 'Caveat: The messages below were generated by the user'
                },
                timestamp: '2023-01-01T12:00:00Z'
            };

            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg?.role).toBe('user');
            expect(msg?.content).toBe('Caveat: The messages below were generated by the user');
        });
    });

    describe('Filtering Logic', () => {
        it('should filter out ide_opened_file messages', () => {
            const event = {
                type: 'user',
                message: {
                    role: 'user',
                    content: '<ide_opened_file>The user opened the file ...</ide_opened_file>'
                }
            };
            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg).toBeNull();
        });

        it('should preserve content mixed with ide_opened_file', () => {
            const event = {
                type: 'user',
                message: {
                    role: 'user',
                    content: 'hello world\n<ide_opened_file>The user opened the file ...</ide_opened_file>'
                }
            };
            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg).not.toBeNull();
            expect(msg?.content).toBe('hello world');
        });

        it('should filter out empty messages with no tool calls', () => {
            const event = {
                type: 'user',
                message: {
                    role: 'user',
                    content: '   ' // whitespace only
                }
            };
            const msg = ClaudeParser.parseMessage(event as any);
            expect(msg).toBeNull();
        });

        it('should filter out multiple empty assistant messages', () => {
            // Simulate a session with valid user message but empty assistant follow-ups
            // (e.g. tool calls that were filtered or internal events)
            const jsonl = `
{"type":"user","message":{"role":"user","content":"hello"},"sessionId":"sid"}
{"type":"assistant","message":{"role":"assistant","content":""},"sessionId":"sid"}
{"type":"assistant","message":{"role":"assistant","content":"   "},"sessionId":"sid"}
            `;
            const session = ClaudeParser.parseSession(jsonl);
            expect(session).toBeDefined();
            // Should only have the user message "hello"
            expect(session?.messages).toHaveLength(1);
            expect(session?.messages[0].content).toBe('hello');
        });
    });

    describe('Title Generation', () => {
        it('should pick first meaningful user message as title', () => {
            const jsonl = `
{"type":"user","message":{"role":"user","content":"<ide_opened_file>...</ide_opened_file>"},"sessionId":"sid"}
{"type":"assistant","message":{"role":"assistant","content":"tool use"},"sessionId":"sid"}
{"type":"user","message":{"role":"user","content":"Actual Title"},"sessionId":"sid"}
            `;
            const session = ClaudeParser.parseSession(jsonl);
            expect(session?.title).toBe('Actual Title');
        });

        it('should fallback to session ID if no meaningful title found', () => {
            const jsonl = `
{"type":"user","message":{"role":"user","content":"<ide_opened_file>...</ide_opened_file>"},"sessionId":"sid-123"}
            `;
            const session = ClaudeParser.parseSession(jsonl);
            // Since the only message is filtered out, session might be null or valid but empty
            // Wait, if parseMessage returns null, it's not added.
            // So messages array is empty. Logic: title: messages[0]? || sessionId
            // But parseSession returns null if messages.length === 0
            expect(session).toBeNull();
        });

        it('should fallback to session ID if only assistant messages exist', () => {
            const jsonl = `
{"type":"assistant","message":{"role":"assistant","content":"hi"},"sessionId":"sid-123"}
             `;
            const session = ClaudeParser.parseSession(jsonl);
            expect(session?.title).toBe('sid-123');
        });
    });

    describe('isSidechain', () => {
        it('should detect sidechain true', () => {
            const line = '{"isSidechain":true}';
            expect(ClaudeParser.isSidechain(line)).toBe(true);
        });

        it('should detect sidechain false', () => {
            const line = '{"isSidechain":false}';
            expect(ClaudeParser.isSidechain(line)).toBe(false);
        });
    });
});
